---
title: "Data Description"
author: "Sviatlana Shakibaei"
date: "2024-02-17"
output:
  html_document:
    df_print: paged
---
```{r}
#Loading Dataset
Lakes <-read.csv(file="https://files.ontario.ca/moe_mapping/downloads/2Water/GLIP/All_Lakes_GLIP.csv",header=T,sep=",")
```

```{r}
#Summary Statistics
summary(Lakes)
```

```{r}
#Structure of the Dataset
str(Lakes)
```

```{r}
#Displaying of the Data Types of all Variables in the Dataset
sapply(Lakes, class)
```

```{r}
#Checking for the Missing Values
sum(is.na(Lakes))
```

```{r}
#Handling the Missing Values
Lakes <- na.omit(Lakes)
```

```{r}
#Viewing the First Few Rows of the Dataset
head(Lakes)
```

```{r}
#Checking the Distribution of a Numeric Variable "VALUE"

#Plotting a Histogram of the Dataset
hist(Lakes$VALUE, main = "Histogram of VALUE")
```

```{r}
#The Kolmogorov-Smirnov Test is Another Statistical Test for Normality
ks.test(Lakes$VALUE, "pnorm", mean = mean(Lakes$VALUE), sd = sd(Lakes$VALUE))
```

```{r}
#Standardizing the Data

#Selecting only Numeric Columns
numeric_columns <- sapply(Lakes, is.numeric)

#Standardizing Numeric Columns in the Dataset
Lakes_standardized <- as.data.frame(scale(Lakes[, numeric_columns]))

#Viewing the First Few Rows of the Standardized Dataset
head(Lakes_standardized)

```

