---
title: "Feature Selection"
author: "Sviatlana Shakibaei"
date: "2024-02-17"
output: pdf_document
---

```{r}
#Loading Dataset
Lakes <-read.csv(file="https://files.ontario.ca/moe_mapping/downloads/2Water/GLIP/All_Lakes_GLIP.csv",header=T,sep=",")

```

```{r}
#Checking for the Missing Values
sum(is.na(Lakes))
```

```{r}
#Handling the Missing Values
Lakes <- na.omit(Lakes)
```

```{r}
#Standardizing the Data

#Selecting only Numeric Columns
numeric_columns <- sapply(Lakes, is.numeric)

#Standardizing Numeric Columns in the Dataset
Lakes_standardized <- as.data.frame(scale(Lakes[, numeric_columns]))

#Viewing the First Few Rows of the Standardized Dataset
head(Lakes_standardized)
```

```{r}
#Features Selection

#Loading Required Libraries
install.packages("corrplot")
library("corrplot")
install.packages("randomForest")
library("randomForest")

#Identifying the Numeric Columns
numeric_columns <- sapply(Lakes, is.numeric)

#Subsetting the Dataset to Include Only Numeric Columns
numeric_data <- Lakes[, numeric_columns]

#Computing the Correlation Matrix
correlation_matrix <- cor(numeric_data)

#Visualizing the Correlation Matrix
corrplot(correlation_matrix, method = "circle")

#Fitting a Random Forest Model to Determine Feature Importance
rf_model <- randomForest(VALUE ~ ., data = Lakes[, numeric_columns], importance = TRUE)

#Extracting Feature Importance Scores
feature_importance <- importance(rf_model)

#Viewing Feature Importance Scores
print(feature_importance)
```

